version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username $DOCKCER_ID --password-stdin $DOCKCER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker-compose build
      - echo Pulling the mysql:5.7 image...
      - docker pull mysql:5.7
      - echo Pulling the nginx:1.18.0 image...
      - docker pull nginx:1.18.0
      - echo Tagging and pushing the images...
      - |
        for service in heewon-blog_frontend-proxy heewon-blog_frontend heewon-blog_backend heewon-blog_db; do
          if [[ "$service" == "heewon-blog_frontend-proxy" ]]; then
            image="nginx:1.18.0"
          elif [[ "$service" == "heewon-blog_db" ]]; then
            image="mysql:5.7"
          fi
          echo "Tagging and pushing the $service image... imgea -> $image ecr -> $ECR_REPOSITORY_URI"
          docker tag $image $ECR_REPOSITORY_URI:$service
          docker push $ECR_REPOSITORY_URI:$service
        done
  post_build:
    commands:
      - echo Build completed on `date`