version: "3"

services:
  # frontend-proxy:
  #   image: nginx:1.18.0
  #   ports:
  #     - "8080:80"
  #   restart: always
  #   volumes:
  #     - "./nginx/frontend-proxy.conf:/etc/nginx/nginx.conf"
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   # volumns 설정은
  #   # 개발 할때는 빈번하게 수정이 일어나서 이부븐을 추가 하는게 좋겠지만, 배포할 때는 이미지 안에 이미 build file과 node_modules도
  #   # 다 추가되어 있기 때문에 이 부분으로 인해 오히려 빌드파일이 없다. next 명령어를 찾을 수 없다 라는 등의 에러가 나왔다.
  #   # 2023/01/08 yarn dev로 변경했기 때문에 지속적인 업데이트를 컨테이너와 연결시켜야 되서 volumns를 사용!
  #   volumes:
  #     - ./frontend:/app # binding
  db:
    platform: linux/x86_64 # M1은 5.7 설치를 위해 이렇게 해야한다.
    image: mysql:5.7
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hwblog
      MYSQL_USER: ghw
      MYSQL_PASSWORD: heewon
    volumes:
      - .dbdata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
    depends_on:
      - db
